### ISSUE TITLE
Incorrect definition of `ceil` in 13-a-prelude.md

### ISSUE THREAD

**Issue by jordancurve** [razetime/ngn-k-tutorial#26]
13-a-prelude.md says:

> You can simply delete this, and remember `1+_` as ceil, cause that removes the need for a word.

But ceil and `1+_` are different. At https://ngn.bitbucket.io/k/#r, `ceil 4` returns 4, while `1+_4` returns 5. Transcript:

```
 ceil:-_-:
 ceil 4
4
 1+_4
5
```

**Comment by razetime** [comment]
right, that is only correct for positive integers. I will fix this.
