### ISSUE TITLE
Thoughts on mixed base conversion

### ISSUE THREAD

**Issue by hmkemppainen** [razetime/ngn-k-tutorial#32]
Looking at the first exercise under 9.3: 

> Write a function to convert seconds into hours, minutes and seconds, using `\`.

My first instinct would be something like `{60 60\x}`.  However, this does not preserve hours:
```
 60 60\3600
0 0
```
After some trial and terror, I discovered that a zero allows overflowing digits to carry over without a limit, thus we can count any number of hours:
```
 0 60 60\3600
1 0 0
 0 60 60\172800
48 0 0
```
I don't think this is documented in the book or in the built-in help.

I disagree with the given code solution ..
```
bs:24 60 60\ / mixed base conversion.
```
.. because 172800 seconds most certainly isn't equal to zero hours, zero minutes, and zero seconds!
```
 bs 172800
0 0 0
```

I guess the exercise was meant to mirror the example from a few paragraphs above:

> For mixed radix, we can try some time conversion: hours, minutes and seconds to seconds:
>
> ```
>  24 60 60/2 46 40
> 10000
> ```

But this one at least allows inputting multiples of 24 hours without overflowing them to zero, so there's a bit of asymmetry:
```
 24 60 60/48 0 0
172800
 24 60 60\24 60 60/48 0 0
0 0 0
```
I guess the 24 here isn't serving any purpose unless you're actually trying to convert days.  Then perhaps the example should be adjusted to input days:
```
 0 24 60 60\0 24 60 60/2 0 0 0
2 0 0 0
 0 24 60 60\0 24 60 60/0 48 0 0
2 0 0 0
```
This would be a proper mixed radix conversion and not just base-60 :)

**Comment by razetime** [comment]
hm, yes, this is sound reasoning. I will change it shortly.
