### ISSUE TITLE
Description of each in chapter 5 contains an example for reverse

### ISSUE THREAD

**Issue by LyricLy** [razetime/ngn-k-tutorial#5]
Seen here:

> ### `f' x` Each
>
> **Symbol:** `'`
>
> **Args:** `function' array`
>
> **Description:** Apply function to each element of array.
>
> **For example, to reverse an array, we can use the `|` verb:**
>
> ```
>  |1 2 3
> 3 2 1
> ```

**Comment by razetime** [comment]
fixed in 04b26c2
